name: Auto-update tipikroya.m3u

on:
  schedule:
    - cron: '*/10 * * * *' # update tiap 10 menit
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Generate tipikroya.m3u
        run: |
          python <<'EOF'
          import requests
          import json

          url = "https://hypera.live/api/stats"
          resp = requests.get(url)
          data = resp.json()

          with open("tipikroya.m3u", "w", encoding="utf-8") as f:
              f.write("#EXTM3U\n")
              for ch in data.get("channels", []):
                  name = ch.get("name", ch.get("id", "unknown"))
                  poster = ch.get("poster", "")
                  stream = ch.get("url", "")
                  if stream.endswith(".m3u8"):
                      f.write(f'#EXTINF:-1 tvg-logo="{poster}",{name}\n')
                      f.write(f'{stream}\n')
          EOF

      - name: Commit & Push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add tipikroya.m3u
          git commit -m "Auto-update tipikroya.m3u" || echo "No changes to commit"
          git push https://x-access-token:${PAT_TOKEN}@github.com/gasskeunn1/rahasia.git HEAD:main
