name: Update Playlist

on:
  schedule:
    - cron: "*/1 * * * *"   # jalan tiap 1 menit
  workflow_dispatch:        # bisa dijalankan manual

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update.py

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ -n "$(git status --porcelain)" ]]; then
            git add playlist*.m3u index.html errors.log || true
            git commit -m "Update playlist [skip ci]" || true
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi
