name: Update tipikroya.m3u

on:
  schedule:
    - cron: "0 * * * *"  # setiap jam
  workflow_dispatch:  # bisa manual trigger juga

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run update.py
        env:
          HYPERA_COOKIES: ${{ secrets.HYPERA_COOKIES }}
        run: python update.py

      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update tipikroya.m3u"
          file_pattern: tipikroya.m3u
