name: Update Playlist

on:
  schedule:
    - cron: "*/1 * * * *"   # tiap menit
  workflow_dispatch:        # bisa juga manual run dari Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip requests

      - name: Run update script
        run: |
          python update.py

      - name: Commit & Push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add playlist.m3u errors.log || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update playlist & errors [skip ci]"
            git push
          fi
