name: Update Hypera Playlist with Logo

on:
  schedule:
    - cron: "*/5 * * * *"   # setiap 5 menit
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      # Checkout branch main
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: pip install requests

      # Jalankan script update.py
      - name: Run update script
        run: python update.py

      # Commit & push dengan GITHUB_TOKEN
      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tipikroya.m3u errors.log last_response.html || true
          git commit -m "Auto-update tipikroya.m3u with refreshed token [skip ci]" || echo "No changes to commit"
