name: Update Playlist

on:
  schedule:
    - cron: "*/1 * * * *"   # jalan tiap 1 menit
  workflow_dispatch:        # bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages   # langsung kerja di branch gh-pages

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run update script
        run: |
          python update.py || true   # kalau error, tetap lanjut commit

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u errors.log last_response.html || true
          git commit -m "Update playlist [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
