name: Update M3U Playlist

on:
  schedule:
    - cron: '*/10 * * * *'  # Update tiap 10 menit
  workflow_dispatch:

jobs:
  update_playlist:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install requests

    - name: Run update script
      run: python update.py

    - name: Commit & push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto-update tipikroya.m3u
        branch: main
        file_pattern: tipikroya.m3u
        author_name: github-actions
        author_email: github-actions@users.noreply.github.com
