name: Update Playlist

on:
  schedule:
    - cron: "*/1 * * * *"   
  workflow_dispatch:        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update.py
        run: python update.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u playlist_*.m3u index.html
          git commit -m "Auto update playlist [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
