name: Update M3U

on:
  schedule:
    - cron: '*/30 * * * *'  # setiap 30 menit
  workflow_dispatch:  # bisa manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        playwright install

    - name: Run update script
      run: python update.py
      env:
        HYPERA_COOKIES: ${{ secrets.HYPERA_COOKIES }}
