name: Update M3U

on:
  schedule:
    - cron: "0 * * * *"  # contoh tiap 1 jam sekali
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run update.py
        run: python update.py

      - name: Upload debug files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-files
          path: |
            last_response.html
            errors.log
            tipikroya.m3u
