name: Update Hypera Playlist

on:
  schedule:
    - cron: "*/1 * * * *"   # jalan tiap 5 menit
  workflow_dispatch:         # bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update.py

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tipikroya.m3u errors.log || true
          git commit -m "Auto-update tipikroya.m3u [skip ci]" || echo "No changes"
          git push origin gh-pages
